/* This file is generated by scripts/sync-imported-jianpu.mjs. */

export interface imported_jianpu_page {
  index: number;
  file: string;
  url: string;
  width: number;
  height: number;
}

export interface imported_jianpu_preview_image {
  url: string;
  alt: string;
  width: number;
  height: number;
}

export interface imported_jianpu_entry {
  id: string;
  title: string;
  attribution: string;
  source_title: string;
  source_url: string;
  directory: string;
  page_count: number;
  preview_image: imported_jianpu_preview_image;
  pages: imported_jianpu_page[];
  rights_note: string;
}

export const imported_jianpu_entries: imported_jianpu_entry[] = [
  {
    "id": "imported-01",
    "title": "《孤勇者》",
    "attribution": "唐恬",
    "source_title": "孤勇者钢琴简谱 数字双手 唐恬-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/1010687.htm",
    "directory": "001-孤勇者钢琴简谱-数字双手-唐恬-虫虫钢琴",
    "page_count": 9,
    "preview_image": {
      "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《孤勇者》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 7,
        "file": "page-007.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-007.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 8,
        "file": "page-008.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-008.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 9,
        "file": "page-009.png",
        "url": "/materials/jianpu-imported/001-%E5%AD%A4%E5%8B%87%E8%80%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-009.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-02",
    "title": "《Komorebi》",
    "attribution": "原站标题未标注作者",
    "source_title": "Komorebi钢琴简谱 数字双手-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/981040.htm",
    "directory": "002-Komorebi钢琴简谱-数字双手-虫虫钢琴",
    "page_count": 8,
    "preview_image": {
      "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《Komorebi》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 7,
        "file": "page-007.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-007.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 8,
        "file": "page-008.png",
        "url": "/materials/jianpu-imported/002-Komorebi%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-008.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-03",
    "title": "《Flower Dance》",
    "attribution": "原站标题未标注作者",
    "source_title": "Flower Dance钢琴简谱 数字双手-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/974936.htm",
    "directory": "003-Flower-Dance钢琴简谱-数字双手-虫虫钢琴",
    "page_count": 8,
    "preview_image": {
      "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《Flower Dance》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 7,
        "file": "page-007.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-007.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 8,
        "file": "page-008.png",
        "url": "/materials/jianpu-imported/003-Flower-Dance%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-008.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-04",
    "title": "《所念皆星河》",
    "attribution": "原站标题未标注作者",
    "source_title": "所念皆星河钢琴简谱 数字双手-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/942280.htm",
    "directory": "004-所念皆星河钢琴简谱-数字双手-虫虫钢琴",
    "page_count": 8,
    "preview_image": {
      "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《所念皆星河》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 7,
        "file": "page-007.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-007.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 8,
        "file": "page-008.png",
        "url": "/materials/jianpu-imported/004-%E6%89%80%E5%BF%B5%E7%9A%86%E6%98%9F%E6%B2%B3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-008.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-05",
    "title": "《这世界那么多人》",
    "attribution": "王海涛",
    "source_title": "这世界那么多人钢琴简谱 数字双手 王海涛-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/982245.htm",
    "directory": "006-这世界那么多人钢琴简谱-数字双手-王海涛-虫虫钢琴",
    "page_count": 7,
    "preview_image": {
      "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《这世界那么多人》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 7,
        "file": "page-007.png",
        "url": "/materials/jianpu-imported/006-%E8%BF%99%E4%B8%96%E7%95%8C%E9%82%A3%E4%B9%88%E5%A4%9A%E4%BA%BA%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E7%8E%8B%E6%B5%B7%E6%B6%9B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-007.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-06",
    "title": "《白月光与朱砂痣》",
    "attribution": "黄千芊 / 王佳滢",
    "source_title": "白月光与朱砂痣钢琴简谱 数字双手 黄千芊/王佳滢-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/971689.htm",
    "directory": "007-白月光与朱砂痣钢琴简谱-数字双手-黄千芊-王佳滢-虫虫钢琴",
    "page_count": 6,
    "preview_image": {
      "url": "/materials/jianpu-imported/007-%E7%99%BD%E6%9C%88%E5%85%89%E4%B8%8E%E6%9C%B1%E7%A0%82%E7%97%A3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E9%BB%84%E5%8D%83%E8%8A%8A-%E7%8E%8B%E4%BD%B3%E6%BB%A2-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《白月光与朱砂痣》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/007-%E7%99%BD%E6%9C%88%E5%85%89%E4%B8%8E%E6%9C%B1%E7%A0%82%E7%97%A3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E9%BB%84%E5%8D%83%E8%8A%8A-%E7%8E%8B%E4%BD%B3%E6%BB%A2-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/007-%E7%99%BD%E6%9C%88%E5%85%89%E4%B8%8E%E6%9C%B1%E7%A0%82%E7%97%A3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E9%BB%84%E5%8D%83%E8%8A%8A-%E7%8E%8B%E4%BD%B3%E6%BB%A2-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/007-%E7%99%BD%E6%9C%88%E5%85%89%E4%B8%8E%E6%9C%B1%E7%A0%82%E7%97%A3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E9%BB%84%E5%8D%83%E8%8A%8A-%E7%8E%8B%E4%BD%B3%E6%BB%A2-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/007-%E7%99%BD%E6%9C%88%E5%85%89%E4%B8%8E%E6%9C%B1%E7%A0%82%E7%97%A3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E9%BB%84%E5%8D%83%E8%8A%8A-%E7%8E%8B%E4%BD%B3%E6%BB%A2-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/007-%E7%99%BD%E6%9C%88%E5%85%89%E4%B8%8E%E6%9C%B1%E7%A0%82%E7%97%A3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E9%BB%84%E5%8D%83%E8%8A%8A-%E7%8E%8B%E4%BD%B3%E6%BB%A2-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/007-%E7%99%BD%E6%9C%88%E5%85%89%E4%B8%8E%E6%9C%B1%E7%A0%82%E7%97%A3%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E9%BB%84%E5%8D%83%E8%8A%8A-%E7%8E%8B%E4%BD%B3%E6%BB%A2-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-07",
    "title": "《Summer》",
    "attribution": "原站标题未标注作者",
    "source_title": "Summer钢琴简谱 数字双手-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/938905.htm",
    "directory": "008-Summer钢琴简谱-数字双手-虫虫钢琴",
    "page_count": 6,
    "preview_image": {
      "url": "/materials/jianpu-imported/008-Summer%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《Summer》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/008-Summer%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/008-Summer%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/008-Summer%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/008-Summer%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/008-Summer%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/008-Summer%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-08",
    "title": "《人世间》",
    "attribution": "唐恬",
    "source_title": "人世间钢琴简谱 数字双手 唐恬-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/1019798.htm",
    "directory": "009-人世间钢琴简谱-数字双手-唐恬-虫虫钢琴",
    "page_count": 6,
    "preview_image": {
      "url": "/materials/jianpu-imported/009-%E4%BA%BA%E4%B8%96%E9%97%B4%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《人世间》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/009-%E4%BA%BA%E4%B8%96%E9%97%B4%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/009-%E4%BA%BA%E4%B8%96%E9%97%B4%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/009-%E4%BA%BA%E4%B8%96%E9%97%B4%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/009-%E4%BA%BA%E4%B8%96%E9%97%B4%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/009-%E4%BA%BA%E4%B8%96%E9%97%B4%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/009-%E4%BA%BA%E4%B8%96%E9%97%B4%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E5%94%90%E6%81%AC-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-09",
    "title": "《KD Searching》",
    "attribution": "原站标题未标注作者",
    "source_title": "KD_Searching钢琴简谱 数字双手-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/1017452.htm",
    "directory": "010-KD_Searching钢琴简谱-数字双手-虫虫钢琴",
    "page_count": 3,
    "preview_image": {
      "url": "/materials/jianpu-imported/010-KD_Searching%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《KD Searching》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/010-KD_Searching%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/010-KD_Searching%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/010-KD_Searching%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  },
  {
    "id": "imported-10",
    "title": "《漠河舞厅》",
    "attribution": "柳爽",
    "source_title": "漠河舞厅钢琴简谱 数字双手 柳爽-虫虫钢琴",
    "source_url": "https://www.gangqinpu.com/jianpu/1009389.htm",
    "directory": "011-漠河舞厅钢琴简谱-数字双手-柳爽-虫虫钢琴",
    "page_count": 8,
    "preview_image": {
      "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
      "alt": "《漠河舞厅》 导入简谱第一页预览",
      "width": 483,
      "height": 680
    },
    "pages": [
      {
        "index": 1,
        "file": "page-001.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-001.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 2,
        "file": "page-002.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-002.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 3,
        "file": "page-003.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-003.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 4,
        "file": "page-004.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-004.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 5,
        "file": "page-005.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-005.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 6,
        "file": "page-006.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-006.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 7,
        "file": "page-007.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-007.png",
        "width": 483,
        "height": 680
      },
      {
        "index": 8,
        "file": "page-008.png",
        "url": "/materials/jianpu-imported/011-%E6%BC%A0%E6%B2%B3%E8%88%9E%E5%8E%85%E9%92%A2%E7%90%B4%E7%AE%80%E8%B0%B1-%E6%95%B0%E5%AD%97%E5%8F%8C%E6%89%8B-%E6%9F%B3%E7%88%BD-%E8%99%AB%E8%99%AB%E9%92%A2%E7%90%B4/page-008.png",
        "width": 483,
        "height": 680
      }
    ],
    "rights_note": "该条目已进入授权教学版，当前已根据原始 CCMZ 数据整理为整首结构化教学谱；原谱页图保留用于来源对照。"
  }
];
